### ISSUE TITLE
View Deliveries doesn't display existing deliveries

### ISSUE THREAD

**Issue by pinalj** [TycheSoftwares/product-delivery-date-for-woocommerce-lite#102]
View Deliveries is not displaying any deliveries.

1. Count of view is 0, even though records are displayed.
2. Qty & amount is also being displayed as 0

**Comment by apeksha10** [comment]
After deleting the plugin, data-based does not delete the edit product information
If I enable the "Enable Deleting Order Details" then all data should be deleted
see the screenshot : https://www.screencast.com/t/GvYRCUjbu5w

Hence re-open this issue

**Comment by apeksha10** [comment]
Now onwards View Deliveries feature works in Prddd Pro users.

So I am closing this issue.
