### ISSUE TITLE
Delivery Calendar does not pop up

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/product-delivery-date-for-woocommerce-lite#116]
**Describe the bug**
Delivery Calendar does not pop up

After taking the latest git copy, On product front end the delivery calendar not popping up and console show some error.

see the screenshot: https://www.screencast.com/t/XdjJZhihLo34

Note: The above error is coming when you go the product page.

**Comment by Shasvat7** [comment]
This bug is not coming on staging site..
