### ISSUE TITLE
Product settings not saved on Imported products from xml file.

### ISSUE THREAD

**Issue by nitin-ts** [TycheSoftwares/product-delivery-date-for-woocommerce-lite#122]
**Describe the bug**
I have imported products from the XML file and when I want to enable Product delivery settings for that product then it won't allow me to so.

**To Reproduce**
1. I have attached the file which I used to import products.
[products.zip](https://github.com/TycheSoftwares/product-delivery-date-for-woocommerce-lite/files/4923210/products.zip)
2. After importing the products then edit one product to enable Product delivery settings and make changes as per requirements and then click on the update button to save that product.
3. Now you can see that the settings is not saved.
4. But when you create a new product and then enable settings for Product delivery then it will allow you to save those settings.

**Expected behavior**
It should work with all products.

**Screenshots or Video**
https://www.screenpresso.com/=XMcWd

**Comment by ashokrane** [comment]
@nitin-ts This issue may also be present in the Pro version.
