### ISSUE TITLE
We should add a class to div instead of inline styles on the below-mentioned line.

### ISSUE THREAD

**Issue by priyanka-tychesoftwares** [TycheSoftwares/product-delivery-date-for-woocommerce-lite#126]
**Describe the bug**
We should add a class to div instead of inline styles on the below-mentioned line.

Line of code on line 64 in class-prdd-lite-process.php :
print ( ‘<div class=”WHATEVERTHENAMEYOUWANT”><label class=”delivery_date_label”>’ . esc_html_e( ‘Delivery Date:’, ‘woocommerce-prdd-lite’ ) . ‘</label>’ );

The client wants to set the class to the div,

https://wordpress.org/support/topic/width-calendar-70-inside-html-class-please/

**Comment by nitin-ts** [comment]
Hello,

I have removed inline CSS and added those in the CSS file as described.

I have also uploaded the changed files for this issue.

Please review the changes.

Thanks.
