### ISSUE TITLE
Limit deliveries per product variations per day

### ISSUE THREAD

**Issue by Agoralemonade** [TycheSoftwares/product-delivery-date-for-woocommerce-lite#137]
Hi there! 

The plugin looks amazing and we are about to buy it for a client but we are facing a particular question.
Surely this has been asked already but I could not find anything on that matter.

_**Is there a a way to make it work with product variations?**_

I would like to be able to **limit the number of deliveries per variation of a product** (i.e: I have 3 variations of a t-shirt, black, red and yellow, with 3 different stocks quantities, and I would like to limit orders for each every day with a specific stocks quantity).  

I tried your live demo and created variations of a product, but there does not seem to be anything at the variation level to enable that - only at the product level. Even though your product page says "Integrates easily with Variable Products of WooCommerce" - am I missing something?

Thanks in advance,
Paul

<img width="1392" alt="Capture d’écran 2020-11-12 à 09 50 16" src="https://user-images.githubusercontent.com/39024909/98917532-c9a69d00-24cc-11eb-9dd6-4d9ea7ac8b93.png">
<img width="1242" alt="Capture d’écran 2020-11-12 à 09 50 12" src="https://user-images.githubusercontent.com/39024909/98917538-cc08f700-24cc-11eb-9651-c6b243f580d7.png">

**Comment by upenkapse** [comment]
Hi Paul,

I am afraid there is no direct way to limit the number of deliveries per day based on product variations right now with our Product Delivery Date plugin.

However, I recommend you to take a look at our Booking & Appointment plugin once: 
https://www.tychesoftwares.com/store/premium-plugins/woocommerce-booking-plugin/

The Booking & Appointment plugin does allow you to set the number of bookings per day at the variation level. Yes, the plugin is dedicatedly built for accepting bookings but with some label changes on the frontend, you could use the booking date field as a delivery date field too. 

Let me know your thoughts.

**Comment by Agoralemonade** [comment]
Hi Upenkapse,

Thanks a lot for your reply,
We went with the plugin you suggested, it solves a great deal of our problem, so thanks a lot for this.
We indeed managed changing the label fields to adapt them to our store.

I might have a question or two concerning that specific plugin but I will ask them on the appropriate Github.

Wishing you a nice day,
Paul

**Comment by apeksha10** [comment]
I am closing this issue as per above comment
