### ISSUE TITLE
The number of months to show in the calendar shows 1 even If I set as 2 before the migration process.

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/product-delivery-date-for-woocommerce-lite#138]
**Describe the bug**
The number of months to show in the calendar shows 1 even If I set as 2 before the migration process.

**To Reproduce**
1. Take a live copy of the lite plugin from wp.org 
2. set "Number of months to show in the calendar" as 2
3. Update database notice appears and clicks update database button.
4. Install Prdd Pro plugin
but here I noticed that the Number of the month shows in the calendar as 1 which is wrong.
https://www.screencast.com/t/KJnYQliXrByq

**Expected behavior**
The number of Months to show in the calendar should  show the correct value

**Comment by Shasvat7** [comment]
This issue is not been replicated hence, closing the issue.
Check this Video:-  https://www.awesomescreenshot.com/video/1775808?key=c7b909a5e5f4c22c27216b522e99e1f8

**Comment by apeksha10** [comment]
With the latest git copy, I am not able to replicate the above issue.

Hence put fixed label
