### ISSUE TITLE
After we activate the Pro plugin the Lite plugin is deactivated but the menu in the Left is still coming from the Lite plugin.

### ISSUE THREAD

**Issue by Shasvat7** [TycheSoftwares/product-delivery-date-for-woocommerce-lite#142]
**Describe the bug**
Once we activate the Pro plugin the Lite plugin is deactivated but the menu will be coming in the Left from the lite plugin.
**To Reproduce**

1. Install & activate the Lite plugin
2. Then install and activate the Pro plugin you will see the Lite plugin is deactivated but the menu is still coming on the left. 
Screenshot :- https://prnt.sc/vlxo6q

**Expected behavior**
Menu from the lite plugin should not come.

**Comment by apeksha10** [comment]
With the latest git copy, the above issue is still replicated.

see the screenshot : https://www.screencast.com/t/xNPnJVL4Y0F

**Comment by apeksha10** [comment]
With the very latest live copy the above issue is not replicated

Hence I have closed this issue
