### ISSUE TITLE
Add "Settings" link on the Plugins page

### ISSUE THREAD

**Issue by ashokrane** [TycheSoftwares/product-delivery-date-for-woocommerce-lite#151]
On the Plugins page: https://prnt.sc/w25dwn

Please move the "Reset Usage Tracking" to show up after the "View details" on the right side.

And in place of "Reset Usage Tracking", please put the "Settings" link & when clicked, it should go to the Product Delivery Date -> Settings page.

**Comment by apeksha10** [comment]
This is a good enhancement. I think we can implement the same

**Comment by nidhitatosaniya** [comment]
Please move the "Reset Usage Tracking" to show up after the "View details" on the right side.

**Comment by nidhitatosaniya** [comment]
Please move the "Reset Usage Tracking" to show up after the "View details" on the right side.

**Comment by nidhitatosaniya** [comment]
Please move the "Reset Usage Tracking" to show up after the "View details" on the right side.
There is no changes in "Reset Usage Tracking" link it displays like see screenshot here : https://prnt.sc/3TOoCTCfk_pv
Hence I re-opening it.
