### ISSUE TITLE
Date picker field is too small on front end.

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/product-delivery-date-for-woocommerce-lite#24]
I am testing with beta version of WordPress 4.9-RC2 copy

On product front end the date picker field shows too small i am not able to see the proper delivery date.
https://www.screencast.com/t/S8RvuxQap2DA
 I am using Tweety Seventeen theme

I check this on Enfold and Twenty Eleven theme it works fine

**Comment by ashokrane** [comment]
Works fine.
