### ISSUE TITLE
Product page scrolls to Product delivery date meta box when adding a new product

### ISSUE THREAD

**Issue by ashokrane** [TycheSoftwares/product-delivery-date-for-woocommerce-lite#29]
When I click on Add New in Products, the Add new product page scrolls down to the Product Delivery Date meta box. This is happening because I think the focus is set to the Weekdays field. This should not happen.

https://screencast.com/t/IiPeD83SZXA

**Comment by Chetna1510** [comment]
I could not able to replicate the same issue on my local server and staging site with the latest copy of github. See the video: https://www.screencast.com/t/kj6zvs9k
