### ISSUE TITLE
Some strings are missing in .po file

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/product-delivery-date-for-woocommerce-lite#30]
Translation are not possible as some strings are missing in.po file

see the screenshot: https://www.screencast.com/t/huOhwOojVgVg ( We should update .po file by adding all these strings like. weekdays, Delivery days Available, Minimum Delivery preparation time (in hours), Number of Dates to choose) 
screenshot of poedit file : https://www.screencast.com/t/E8V0GVJyO

**Comment by apeksha10** [comment]
still..some string is not added like weekdays name
https://www.screencast.com/t/EPcfH1Gety

Weekdays name strings are not present in poedit file

see the video : https://www.screencast.com/t/X2U4sylZ

hence re-open this issue

**Comment by Chetna1510** [comment]
Weekdays name cannot be translated. As it is in the Javascript array. Hence I am closing this issue.
