### ISSUE TITLE
Delivery Icon is showing at the below of delivery field.

### ISSUE THREAD

**Issue by Chetna1510** [TycheSoftwares/product-delivery-date-for-woocommerce-lite#34]
Delivery Icon is showing at the below of delivery field.

https://www.screencast.com/t/G7qDAohig

**Comment by apeksha10** [comment]
Still.. Delivery Icon does not show proper place

see the screenshot : https://www.screencast.com/t/RpWqlTnyVTU

Hence Re-open this issue
